language: java

jdk: -openjdk8 

addons:
  sonarcloud:
    organization: "pippopaperino"
    token:
      secure: "u5uwfCPxxG6AYwCQP5Xl8L3Gug7AxBeBwn3+c99wAQsoDtdX1aqgHZatAV5zmfJ1RP/8x3uDjkhdYrO77mDwov2J04Yn19xjW3Ndw4wSDwxYgaMJpSjOiNRKFabN1z8DxAWe8S03DSp30ZilyBKnOSfDLRKuAjopobigSnK14R1dAog9mvDxU7KTmodjPzDfbbLkAd6GOr1B9r47bmZQj869feLIZAGQs9cQXbOIXlpk27jtArQOfeKT2LF1HWWlNpbuvywL67ab68GkzducXCTes8fy7iFupJAicPK/9Lgzijimk8lEKjFDKSWzPjbvHtOR+ySakTuJ3wYrdyTfGBR5TUwN1l1C3RtAUCgBGXj5CFV7+CG5kIv4QAHg4fsh5xBttIfba3qN9XQcbTNJ4s8+0dMZyX5nphIDhn+UiPt5vwqhJxEKy9wPbZIRLIx5NNrOJHh7VjqrXrC+MutDnNhHrjo2HpbWmVKUuC2Kl9bTSCVWPs4wkwQp08MFdN584eplhJ0lCP6QJhqovXIZ2tLbVsUGOyQa1VfYs77SV+kUw4bprtvwTCRR9XQaUXQo8CQ1d0WPH4Gc2hLcI0P/Zw38A4emhclSRjNbnn6xaUJZYdiPPA5+D0jmAv3ikUIepvTcwIjo9kG9eQxbkiVm6v1vzx7ZR0R7QYyvHuIBq24="

script:
  -ant build
script:
  - sonar-scanner
